server:
  port: 8899
spring:
  application:
    name: 动车自动化测试项目
  profiles:
      #激活dev开发环境
      active: dev
  datasource:
      name: train-dev
      druid:
        max-active: 20
        initial-size: 10
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # druid连接池监控
        filter:
          stat:
            enabled: true
        web-stat-filter:
          enabled: true
        stat-view-servlet:
          enabled: true
  mvc:
    servlet:
      load-on-startup: 0
  http:
    encoding:
      force: true
  messages:
    basename: message.restResource
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
    expose-spring-macro-helpers: false
    #应用程序发布，如果有上下文路径，则可以使用
    request-context-attribute: request
  #配置springmvc json序列化器  系统启用fastjson序列化器
  #jackson:
  #  date-format: yyyy-MM-dd HH:mm:ss
  #  time-zone: GMT+8
#mybatis:
#  #实体别名
#  type-aliases-package: smart.industry.train.biz.entity
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    # 开启驼峰命名大法
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: smart.industry.train.biz.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

security:
  basic:
    authorize-mode: none

debug: true
# 系统参数配置
application:
  param:
     # 重置密码的值
     resetPsw: 123456
